apiVersion: 1

datasources:
  - name: ZoroTimescaleDB
    type: postgres
    uid: zoro-timescaledb
    url: timescaledb:5432
    user: zoro
    secureJsonData:
      password: ${GF_TIMESCALEDB_PASSWORD}
    jsonData:
      database:         zoro
      sslmode:          disable
      maxOpenConns:     10
      maxIdleConns:     2
      connMaxLifetime:  14400
      postgresVersion:  1600
      timescaledb:      true
    isDefault: true
    editable: true
